<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.29" />
    <xacro:property name="base_width" value="0.26" /> <!--0.6 0.4 0.2-->
    <xacro:property name="base_height" value="0.12825" />
    <xacro:property name="wheel_radius" value="0.0425" />
    <xacro:property name="wheel_length" value="0.02" />
    

    <link name = "base_footprint" />

    <link name = "base_link">
        <visual>
            <geometry>
                <box size = "${base_length} ${base_width} ${base_height}"></box>
            </geometry>
            <origin xyz = "0 0 ${base_height / 2.0}" rpy = "0 0 0"></origin>
            <material name = "blue"/>
        </visual>
        <collision>
            <geometry>
                <box size = "${base_length} ${base_width} ${base_height}"></box>
            </geometry>
            <origin xyz = "0 0 ${base_height / 2.0}" rpy = "0 0 0"></origin>
        </collision>
        <xacro:box_inertia m="5.0" l="${2.5*base_length}" w="${2.5*base_width}" h="${2.5*base_height}"
                           xyz="0 0 ${2.5*base_height / 2.0}" rpy="0 0 0" />
    </link>

    <xacro:macro name="wheel_link" params="prefix">
        <link name = "${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius = "${wheel_radius}" length = "${wheel_length}" />
                </geometry>
                <origin xyz = "0 0 0" rpy = "${pi / 2.0} 0 0" />
                <material name = "grey" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius = "${wheel_radius}" length = "${wheel_length}" />
                </geometry>
                <origin xyz = "0 0 0" rpy = "${pi / 2.0} 0 0" />
            </collision>
            <xacro:cylinder_inertia m ="1.0" r="${2.5*wheel_radius}" h="${2.5*wheel_length}" xyz=" 0 0 0" 
                                    rpy="${pi / 2.0} 0 0" />
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="right"/>
    <xacro:wheel_link prefix="left"/>
    <xacro:wheel_link prefix="right_front"/>
    <xacro:wheel_link prefix="left_front"/>

    <joint name = "base_footprint_base_joint" type = "fixed">
        <parent link = "base_footprint" />
        <child link = "base_link" />
        <origin xyz = "0 0 0.1" rpy = "0 0 0" />
    </joint>

    <joint name = "base_right_wheel_joint" type = "continuous">
        <parent link = "base_link" />
        <child link = "right_wheel_link" />
        <origin xyz = "${-base_length / 2.0 + 0.0885} ${-(base_width / 2.0)} 0" rpy = "0 0 0" />
        <axis xyz = "0 1 0" />
    </joint>

    <joint name = "base_left_wheel_joint" type = "continuous">
        <parent link = "base_link" />
        <child link = "left_wheel_link" />
        <origin xyz = "${-base_length / 2.0 + 0.0885} ${(base_width / 2.0)} 0" rpy = "0 0 0" />
        <axis xyz = "0 1 0" />
    </joint>

    <joint name = "base_right_front_wheel_joint" type = "continuous">
        <parent link = "base_link" />
        <child link = "right_front_wheel_link" />
        <origin xyz = "${base_length / 2.0 - 0.0885} ${-(base_width / 2.0)} 0" rpy = "0 0 0" />
        <axis xyz = "0 1 0" />
    </joint>

    <joint name = "base_left_front_wheel_joint" type = "continuous">
        <parent link = "base_link" />
        <child link = "left_front_wheel_link" />
        <origin xyz = "${base_length / 2.0 - 0.0885} ${(base_width / 2.0)} 0" rpy = "0 0 0" />
        <axis xyz = "0 1 0" />
    </joint>

</robot>    